# Generated by Django 4.2.7 on 2025-07-03 12:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='categorias/')),
                ('color_hex', models.CharField(default='#FF6B6B', max_length=7)),
                ('icono', models.CharField(default='fas fa-utensils', max_length=50)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('descripcion_corta', models.CharField(blank=True, max_length=160, verbose_name='Descripción corta')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='recetas/', verbose_name='Imagen')),
                ('url_imagen', models.URLField(blank=True, null=True, verbose_name='URL de Imagen')),
                ('imagen_thumbnail', models.ImageField(blank=True, null=True, upload_to='recetas/thumbnails/')),
                ('ingredientes', models.TextField(verbose_name='Ingredientes')),
                ('pasos', models.TextField(verbose_name='Pasos de preparación')),
                ('notas', models.TextField(blank=True, verbose_name='Notas adicionales')),
                ('tiempo_preparacion', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Tiempo de preparación (minutos)')),
                ('tiempo_coccion', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tiempo de cocción (minutos)')),
                ('porciones', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Número de porciones')),
                ('dificultad', models.CharField(choices=[('facil', 'Fácil'), ('intermedio', 'Intermedio'), ('dificil', 'Difícil')], default='facil', max_length=10, verbose_name='Dificultad')),
                ('tipo_comida', models.CharField(choices=[('desayuno', 'Desayuno'), ('almuerzo', 'Almuerzo'), ('cena', 'Cena'), ('postre', 'Postre'), ('aperitivo', 'Aperitivo'), ('snack', 'Snack'), ('bebida', 'Bebida')], default='almuerzo', max_length=10, verbose_name='Tipo de comida')),
                ('calificacion', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Calificación')),
                ('es_favorita', models.BooleanField(default=False, verbose_name='Favorita')),
                ('vistas', models.PositiveIntegerField(default=0)),
                ('calorias', models.PositiveIntegerField(blank=True, null=True)),
                ('proteinas', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('carbohidratos', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('grasas', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activa', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recetas', to='recetas.categoria')),
            ],
            options={
                'verbose_name': 'Receta',
                'verbose_name_plural': 'Recetas',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('color', models.CharField(default='#FF6B6B', max_length=7)),
            ],
            options={
                'verbose_name': 'Etiqueta',
                'verbose_name_plural': 'Etiquetas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Valoracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comentario', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valoraciones', to='recetas.receta')),
            ],
            options={
                'verbose_name': 'Valoración',
                'verbose_name_plural': 'Valoraciones',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddField(
            model_name='receta',
            name='tags',
            field=models.ManyToManyField(blank=True, to='recetas.tag'),
        ),
        migrations.AddIndex(
            model_name='receta',
            index=models.Index(fields=['titulo'], name='recetas_rec_titulo_a34065_idx'),
        ),
        migrations.AddIndex(
            model_name='receta',
            index=models.Index(fields=['dificultad'], name='recetas_rec_dificul_a869e8_idx'),
        ),
        migrations.AddIndex(
            model_name='receta',
            index=models.Index(fields=['tipo_comida'], name='recetas_rec_tipo_co_372788_idx'),
        ),
        migrations.AddIndex(
            model_name='receta',
            index=models.Index(fields=['es_favorita'], name='recetas_rec_es_favo_a8b04f_idx'),
        ),
    ]
