# 🚀 GitHub Actions - Pipeline Simple para Recetas Gourmet

name: Simple CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.11"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set up environment variables
      run: |
        echo "SECRET_KEY=test-secret-key-for-github-actions" > .env
        echo "DEBUG=True" >> .env
        echo "DATABASE_URL=sqlite:///test.db" >> .env

    - name: Run Django checks
      run: |
        python manage.py check

    - name: Run migrations
      run: |
        python manage.py migrate

    - name: Run tests
      run: |
        python manage.py test --verbosity=2

  lint-basic:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Basic syntax check
      run: |
        python -m py_compile recetas/*.py
        python -m py_compile recetas_project/*.py

  security-basic:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Check for secrets in code
      run: |
        echo "Checking for potential secrets..."
        ! grep -r "password.*=" --include="*.py" . || echo "Warning: Found hardcoded passwords"
        ! grep -r "secret.*=" --include="*.py" . || echo "Warning: Found hardcoded secrets"
        echo "Basic security check completed"
